<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Olasubomi P. Odujebe">

<title>Canada’s Interest Rate Cycle: How Monetary Policy Responded to Rising Inflation</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="Policy_rate_files/libs/clipboard/clipboard.min.js"></script>
<script src="Policy_rate_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Policy_rate_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Policy_rate_files/libs/quarto-html/popper.min.js"></script>
<script src="Policy_rate_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Policy_rate_files/libs/quarto-html/anchor.min.js"></script>
<link href="Policy_rate_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Policy_rate_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Policy_rate_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Policy_rate_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Policy_rate_files/libs/bootstrap/bootstrap-67270d1595a62d14f123c043d4fb2f18.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">1. Introduction</a>
  <ul class="collapse">
  <li><a href="#research-question" id="toc-research-question" class="nav-link" data-scroll-target="#research-question">1.1 Research Question</a></li>
  </ul></li>
  <li><a href="#data-and-methodology" id="toc-data-and-methodology" class="nav-link" data-scroll-target="#data-and-methodology">2. Data and Methodology</a>
  <ul class="collapse">
  <li><a href="#variables" id="toc-variables" class="nav-link" data-scroll-target="#variables">Variables</a></li>
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">2.1 Data Preparation</a></li>
  <li><a href="#analytical-approach" id="toc-analytical-approach" class="nav-link" data-scroll-target="#analytical-approach">2.2 Analytical Approach</a></li>
  <li><a href="#scope-and-limitations" id="toc-scope-and-limitations" class="nav-link" data-scroll-target="#scope-and-limitations">2.3 Scope and Limitations</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">3. Results</a>
  <ul class="collapse">
  <li><a href="#policy-rate-changes" id="toc-policy-rate-changes" class="nav-link" data-scroll-target="#policy-rate-changes">3.1 Policy Rate Changes</a>
  <ul class="collapse">
  <li><a href="#table-1.-summary-statistics-of-canadas-policy-interest-rate-september-2016july-2026" id="toc-table-1.-summary-statistics-of-canadas-policy-interest-rate-september-2016july-2026" class="nav-link" data-scroll-target="#table-1.-summary-statistics-of-canadas-policy-interest-rate-september-2016july-2026">Table 1. Summary Statistics of Canada’s Policy Interest Rate, September 2016–July 2026</a></li>
  <li><a href="#table-2.-major-policy-rate-cycles-september-2016july-2026" id="toc-table-2.-major-policy-rate-cycles-september-2016july-2026" class="nav-link" data-scroll-target="#table-2.-major-policy-rate-cycles-september-2016july-2026">Table 2. Major Policy Rate Cycles, September 2016–July 2026</a></li>
  <li><a href="#figure-1.-canadas-policy-interest-rate-september-2016july-2026" id="toc-figure-1.-canadas-policy-interest-rate-september-2016july-2026" class="nav-link" data-scroll-target="#figure-1.-canadas-policy-interest-rate-september-2016july-2026">Figure 1. Canada’s Policy Interest Rate, September 2016–July 2026</a></li>
  </ul></li>
  <li><a href="#inflation-and-policy-rate-peaks." id="toc-inflation-and-policy-rate-peaks." class="nav-link" data-scroll-target="#inflation-and-policy-rate-peaks.">3.2 Inflation and Policy Rate Peaks.</a>
  <ul class="collapse">
  <li><a href="#table-3.-inflation-and-policy-rate-turning-points-september-2016july-2026" id="toc-table-3.-inflation-and-policy-rate-turning-points-september-2016july-2026" class="nav-link" data-scroll-target="#table-3.-inflation-and-policy-rate-turning-points-september-2016july-2026">Table 3. Inflation and Policy Rate Turning Points, September 2016–July 2026</a></li>
  </ul></li>
  <li><a href="#changes-following-the-peaks." id="toc-changes-following-the-peaks." class="nav-link" data-scroll-target="#changes-following-the-peaks.">3.3 Changes Following the Peaks.</a>
  <ul class="collapse">
  <li><a href="#table-4.-changes-in-inflation-and-policy-rate-following-their-peaks" id="toc-table-4.-changes-in-inflation-and-policy-rate-following-their-peaks" class="nav-link" data-scroll-target="#table-4.-changes-in-inflation-and-policy-rate-following-their-peaks">Table 4. Changes in Inflation and Policy Rate Following Their Peaks</a></li>
  </ul></li>
  <li><a href="#economic-period-comparison" id="toc-economic-period-comparison" class="nav-link" data-scroll-target="#economic-period-comparison">3.4 Economic Period Comparison</a>
  <ul class="collapse">
  <li><a href="#table-5.-average-inflation-and-policy-rate-across-economic-periods" id="toc-table-5.-average-inflation-and-policy-rate-across-economic-periods" class="nav-link" data-scroll-target="#table-5.-average-inflation-and-policy-rate-across-economic-periods">Table 5. Average Inflation and Policy Rate Across Economic Periods</a></li>
  <li><a href="#figure-3.-average-inflation-and-policy-rate-across-economic-periods" id="toc-figure-3.-average-inflation-and-policy-rate-across-economic-periods" class="nav-link" data-scroll-target="#figure-3.-average-inflation-and-policy-rate-across-economic-periods">Figure 3. Average Inflation and Policy Rate Across Economic Periods</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#findings" id="toc-findings" class="nav-link" data-scroll-target="#findings">4. Findings</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">5. Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Canada’s Interest Rate Cycle: How Monetary Policy Responded to Rising Inflation</h1>
<p class="subtitle lead">September 2016 – July 2026</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Olasubomi P. Odujebe </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>One of the Bank of Canada’s main means of affecting economic conditions and ensuring price stability is by adjusting interest rates. In the last ten years, Canada’s monetary policy went through a number of different phases, starting with a period of slow tightening prior to the COVID-19 pandemic, then moving on to emergency cuts in interest rates in 2020, and afterwards undergoing a vigorous tightening phase during the inflation shock of 2022.</p>
<p>The analysis looks at the changes that took place in Canada’s policy interest rate between September 2016 and July 2026 and at the way these changes correlated with movements in consumer price inflation.</p>
<p>The study looks at the timing and size of the changes in the policy interest rate, the way in which inflation has evolved in relation to the Bank of Canada’s 2% target, and the shift from monetary tightening to monetary easing.</p>
<p>The aim is not to determine a causal link between interest rates and inflation, but rather to look at the timing and patterns in the data and to identify the main stages of the cycle of Canada’s monetary policy.</p>
<section id="research-question" class="level2">
<h2 class="anchored" data-anchor-id="research-question">1.1 Research Question</h2>
<p>How did monetary policy respond to rising inflation in Canada between September 2016 and July 2026?</p>
</section>
</section>
<section id="data-and-methodology" class="level1">
<h1>2. Data and Methodology</h1>
<p>This analysis combines two key Canadian macroeconomic indicators: consumer price inflation and the Bank of Canada’s policy interest rate.</p>
<p><strong>Consumer Price Index (CPI)</strong> Monthly Consumer Price Index data were obtained from Statistics Canada. The analysis uses the All-items CPI series, with observations extending from January 2015 through July 2026.</p>
<p><strong>Policy Interest Rate</strong> Daily policy interest rate data were obtained from the Bank of Canada. The analysis uses the target for the overnight rate (V39079), Canada’s key policy interest rate. The original dataset covers September 2016 through August 2026.</p>
<p>Because the inflation data are available monthly through July 2026, the combined analysis covers the common period from September 2016 to July 2026.</p>
<section id="variables" class="level3">
<h3 class="anchored" data-anchor-id="variables">Variables</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 22%">
<col style="width: 77%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>CPI</td>
<td>Monthly All-items Consumer Price Index</td>
</tr>
<tr class="even">
<td>Inflation Rate</td>
<td>Year-over-year percentage change in the All-items CPI</td>
</tr>
<tr class="odd">
<td>Policy Rate</td>
<td>Bank of Canada’s target for the overnight rate</td>
</tr>
</tbody>
</table>
</section>
<section id="data-preparation" class="level2">
<h2 class="anchored" data-anchor-id="data-preparation">2.1 Data Preparation</h2>
<p>The two datasets required different preparation steps before they could be combined. The CPI data were transformed from a wide monthly format into a time-series structure, while the daily policy-rate data were cleaned and converted to monthly frequency.</p>
<p><img src="images/Workflow.png" class="img-fluid"></p>
<p>The resulting dataset contains the monthly All-items CPI, year-over-year inflation rate, and policy interest rate for the common analysis period.</p>
</section>
<section id="analytical-approach" class="level2">
<h2 class="anchored" data-anchor-id="analytical-approach">2.2 Analytical Approach</h2>
<p>The analysis examines Canada’s monetary policy cycle through several complementary approaches.</p>
<p>First, the policy interest rate is examined over time to identify major periods of monetary tightening and easing.</p>
<p>Second, inflation and the policy rate are compared to examine how the two indicators evolved relative to each other and how inflation moved around the Bank of Canada’s 2% target.</p>
<p>Third, the analysis divides the study period into five broad economic phases:</p>
<ul>
<li>Pre-pandemic</li>
<li>Pandemic &amp; Recovery</li>
<li>Inflation Shock &amp; Tightening</li>
<li>Easing</li>
<li>Stabilization</li>
</ul>
<p>Average inflation and the average policy rate are calculated for each phase to compare inflationary conditions with the prevailing monetary policy stance.</p>
<p>Finally, key turning points are identified by measuring the inflation peak, the policy-rate peak, and the time between the two. Changes in inflation and the policy rate following their respective peaks are also calculated.</p>
</section>
<section id="scope-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="scope-and-limitations">2.3 Scope and Limitations</h2>
<p>This analysis is descriptive rather than causal. The comparison of inflation and the policy interest rate identifies patterns, timing, and changes in the two indicators, but it does not establish that changes in the policy rate alone caused subsequent changes in inflation.</p>
<p>Inflation is influenced by multiple economic factors, including supply conditions, energy prices, labour-market conditions, exchange rates, and consumer demand. These factors are outside the scope of this analysis.</p>
</section>
</section>
<section id="results" class="level1">
<h1>3. Results</h1>
<p>This section shows the main results of the analysis. It looks at changes in the policy rate, when inflation and policy-rate peaks happened, and how these varied across major economic periods. Tables and figures highlight the key patterns in the data.</p>
<section id="policy-rate-changes" class="level2">
<h2 class="anchored" data-anchor-id="policy-rate-changes">3.1 Policy Rate Changes</h2>
<p>Throughout the study period the policy rate went through a number of distinct stages. It rose gradually prior to the pandemic, dropped sharply to 0.25% in 2020, and then increased quickly as a result of the inflation shock. After having reached a peak of 5.00% in 2023 the policy rate started to fall.</p>
<section id="table-1.-summary-statistics-of-canadas-policy-interest-rate-september-2016july-2026" class="level3">
<h3 class="anchored" data-anchor-id="table-1.-summary-statistics-of-canadas-policy-interest-rate-september-2016july-2026">Table 1. Summary Statistics of Canada’s Policy Interest Rate, September 2016–July 2026</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Starting policy rate</td>
<td>0.50%</td>
</tr>
<tr class="even">
<td>Ending policy rate</td>
<td>2.25%</td>
</tr>
<tr class="odd">
<td>Minimum policy rate</td>
<td>0.25%</td>
</tr>
<tr class="even">
<td>Maximum policy rate</td>
<td>5.00%</td>
</tr>
<tr class="odd">
<td>Average policy rate</td>
<td>2.02%</td>
</tr>
<tr class="even">
<td>Total rate changes</td>
<td>27</td>
</tr>
<tr class="odd">
<td>Rate increases</td>
<td>15</td>
</tr>
<tr class="even">
<td>Rate decreases</td>
<td>12</td>
</tr>
<tr class="odd">
<td>Net change</td>
<td>+1.75 pp</td>
</tr>
</tbody>
</table>
<p>This table summarizes the overall level and direction of changes in Canada’s policy interest rate during the study period, including the starting and ending rates, the range of rates, and the number of increases and decreases.</p>
</section>
<section id="table-2.-major-policy-rate-cycles-september-2016july-2026" class="level3">
<h3 class="anchored" data-anchor-id="table-2.-major-policy-rate-cycles-september-2016july-2026">Table 2. Major Policy Rate Cycles, September 2016–July 2026</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Policy Cycle</th>
<th>Starting Rate</th>
<th>Ending Rate</th>
<th>Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2017–2018 Tightening</td>
<td>0.50%</td>
<td>1.75%</td>
<td>+1.25 pp</td>
</tr>
<tr class="even">
<td>2020 Pandemic Easing</td>
<td>1.75%</td>
<td>0.25%</td>
<td>−1.50 pp</td>
</tr>
<tr class="odd">
<td>2022–2023 Tightening</td>
<td>0.25%</td>
<td>5.00%</td>
<td>+4.75 pp</td>
</tr>
<tr class="even">
<td>2024–2025 Easing</td>
<td>5.00%</td>
<td>2.25%</td>
<td>−2.75 pp</td>
</tr>
</tbody>
</table>
<p>This table highlights the major tightening and easing phases of Canada’s monetary policy cycle and shows the change in the policy rate within each phase.</p>
</section>
<section id="figure-1.-canadas-policy-interest-rate-september-2016july-2026" class="level3">
<h3 class="anchored" data-anchor-id="figure-1.-canadas-policy-interest-rate-september-2016july-2026">Figure 1. Canada’s Policy Interest Rate, September 2016–July 2026</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/policy_rate_area.png" class="img-fluid figure-img"></p>
<figcaption><strong>Figure 1</strong> captures the evolution of Canada’s monetary policy over the period. Canada moved through a period of gradual tightening before the pandemic, followed by a sharp reduction in the policy rate to 0.25% in 2020. As inflation pressures returned, the Bank of Canada reversed course, raising the rate rapidly to a 5.00% peak in 2023. The rate then began to ease, reaching 2.25% by July 2026, marking a shift from aggressive tightening toward a more stable policy environment.</figcaption>
</figure>
</div>
</section>
</section>
<section id="inflation-and-policy-rate-peaks." class="level2">
<h2 class="anchored" data-anchor-id="inflation-and-policy-rate-peaks.">3.2 Inflation and Policy Rate Peaks.</h2>
<p>During this period, inflation and the policy rate hit their highest levels at different times. Inflation peaked first, and the policy rate reached its peak afterward.</p>
<section id="table-3.-inflation-and-policy-rate-turning-points-september-2016july-2026" class="level3">
<h3 class="anchored" data-anchor-id="table-3.-inflation-and-policy-rate-turning-points-september-2016july-2026">Table 3. Inflation and Policy Rate Turning Points, September 2016–July 2026</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Peak Rate</th>
<th>Date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inflation Rate</td>
<td>8.13%</td>
<td>June 2022</td>
</tr>
<tr class="even">
<td>Policy Interest Rate</td>
<td>5.00%</td>
<td>July 2023</td>
</tr>
</tbody>
</table>
<p>This table identifies the highest observed inflation rate and the highest policy interest rate during the study period and shows the timing of each peak.The policy interest rate reached its peak approximately 13 months after Inflation reached its peak.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/inflation_policy_two_panel.png" class="img-fluid figure-img"></p>
<figcaption><strong>Figure 2</strong> shows how inflation and the policy interest rate changed over time. Inflation rose sharply in 2021–2022, while the policy rate increased later in response. The two peaks occurred 13 months apart, with inflation reaching its peak first.</figcaption>
</figure>
</div>
</section>
</section>
<section id="changes-following-the-peaks." class="level2">
<h2 class="anchored" data-anchor-id="changes-following-the-peaks.">3.3 Changes Following the Peaks.</h2>
<p>After inflation and the policy rate reached their peaks, how much did each decline by July 2026?</p>
<section id="table-4.-changes-in-inflation-and-policy-rate-following-their-peaks" class="level3">
<h3 class="anchored" data-anchor-id="table-4.-changes-in-inflation-and-policy-rate-following-their-peaks">Table 4. Changes in Inflation and Policy Rate Following Their Peaks</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Indicator</th>
<th>Peak</th>
<th>July 2026</th>
<th>Change</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Inflation Rate</td>
<td>8.13%</td>
<td>3.03%</td>
<td>−5.10 pp</td>
</tr>
<tr class="even">
<td>Policy Interest Rate</td>
<td>5.00%</td>
<td>2.25%</td>
<td>−2.75 pp</td>
</tr>
</tbody>
</table>
<p>This table compares the peak levels of inflation and the policy interest rate with their respective levels in July 2026. Inflation fell by 5.10 percentage points, from 8.13% in June 2022 to 3.03% in July 2026. Over the same period, the policy interest rate declined by 2.75 percentage points, from its peak of 5.00% to 2.25% in July 2026.</p>
</section>
</section>
<section id="economic-period-comparison" class="level2">
<h2 class="anchored" data-anchor-id="economic-period-comparison">3.4 Economic Period Comparison</h2>
<p>The analysis period was divided into five broad economic phases to compare inflation and monetary policy conditions across different periods. Table 5 presents the average inflation rate and average policy interest rate for each phase.</p>
<section id="table-5.-average-inflation-and-policy-rate-across-economic-periods" class="level3">
<h3 class="anchored" data-anchor-id="table-5.-average-inflation-and-policy-rate-across-economic-periods">Table 5. Average Inflation and Policy Rate Across Economic Periods</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 27%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Economic Period</th>
<th>Average Inflation</th>
<th>Average Policy Rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-pandemic</td>
<td>1.88%</td>
<td>1.22%</td>
</tr>
<tr class="even">
<td>Pandemic &amp; Recovery</td>
<td>2.06%</td>
<td>0.38%</td>
</tr>
<tr class="odd">
<td>Inflation Shock &amp; Tightening</td>
<td>5.35%</td>
<td>3.41%</td>
</tr>
<tr class="even">
<td>Easing</td>
<td>2.23%</td>
<td>3.56%</td>
</tr>
<tr class="odd">
<td>Stabilization</td>
<td>2.62%</td>
<td>2.25%</td>
</tr>
</tbody>
</table>
<p>This table compares the average inflation rate with the average policy interest rate across five broad economic phases, highlighting how monetary policy conditions differed across the study period.</p>
</section>
<section id="figure-3.-average-inflation-and-policy-rate-across-economic-periods" class="level3">
<h3 class="anchored" data-anchor-id="figure-3.-average-inflation-and-policy-rate-across-economic-periods">Figure 3. Average Inflation and Policy Rate Across Economic Periods</h3>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/period_comparison_chart.png" class="img-fluid figure-img"></p>
<figcaption><strong>Figure 3.</strong> The comparison between the periods reveals major differences in both inflation and the conditions of monetary policy. The key point is that inflation dropped from the Inflation Shock &amp; Tightening period to the Easing period, although the policy rate remained fairly high before falling during the Stabilization period. Average inflation was at its highest in the Inflation Shock &amp; Tightening period, amounting to 5.35%, as against an average policy rate of 3.41%. In the following Easing period, average inflation fell to 2.23% while the average policy rate stayed relatively high at 3.56%. By the Stabilization period, average inflation had increased slightly to 2.62%, the average policy rate having at the same time dropped to 2.25%.</figcaption>
</figure>
</div>
</section>
</section>
</section>
<section id="findings" class="level1">
<h1>4. Findings</h1>
<p>The results show a clear shift in Canada’s monetary policy over the study period. The policy rate moved from gradual tightening before the pandemic to a sharp reduction in 2020, followed by an aggressive tightening cycle as inflation increased. The rate reached 5.00% in 2023 before easing to 2.25% by July 2026.</p>
<p>Inflation also followed a distinct pattern. It rose sharply during 2021–2022 and reached a peak of 8.13% in June 2022. The policy rate reached its peak of 5.00% in July 2023, creating a 13-month difference between the two peaks. This suggests that inflation and monetary policy did not move at exactly the same time, which is consistent with the delayed effects often associated with monetary policy. However, the analysis is descriptive and does not establish a causal relationship.</p>
<p>Following the peaks, both inflation and the policy rate declined. By July 2026, inflation had fallen to 3.03%, while the policy rate had declined to 2.25%. Inflation therefore fell by 5.10 percentage points from its peak, compared with a 2.75 percentage-point decline in the policy rate.</p>
<p>Across the five economic periods, the results also show how monetary conditions changed over time. Inflation was highest during the Inflation Shock &amp; Tightening period, while the policy rate remained elevated during the Easing period. This reflects the fact that the policy rate can remain restrictive even after inflation begins to fall.</p>
</section>
<section id="conclusion" class="level1">
<h1>5. Conclusion</h1>
<p>This analysis examined how Canada’s monetary policy changed as inflation moved through different stages between September 2016 and July 2026. The results show that the policy rate moved from very low levels during the pandemic to a peak of 5.00% as inflation increased, before gradually declining as inflation eased.</p>
<p>Inflation reached its peak before the policy rate, with a 13-month difference between the two peaks. While this timing is consistent with a delayed monetary policy response, the analysis is descriptive and cannot establish a causal relationship. Overall, the results show a clear shift from accommodative monetary policy during the pandemic to strong tightening during the inflation shock, followed by a period of easing.</p>
</section>
<section id="references" class="level1">
<h1>References</h1>
<p>Bank of Canada. (2026). <em>Canadian interest rates and monetary policy variables: 10-year lookup</em>. <a href="https://www.bankofcanada.ca/rates/interest-rates/canadian-interest-rates/" class="uri">https://www.bankofcanada.ca/rates/interest-rates/canadian-interest-rates/</a></p>
<p>Statistics Canada. (2026). <em>Consumer Price Index, monthly, not seasonally adjusted</em> (Table 18-10-0004-01). <a href="https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401" class="uri">https://www150.statcan.gc.ca/t1/tbl1/en/tv.action?pid=1810000401</a></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>